### ISSUE TITLE
circrnasponging not find

### ISSUE THREAD

**Issue by Cesnl** [biomedbigdata/circRNA-sponging#11]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/circrnasponging pipeline documentation](https://nf-co.re/nf-core/circrnasponging/usage)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag: 

## Additional context

nextflow run nf-core/circrnasponging -profile test,docker
N E X T F L O W  ~  version 23.10.0
Pulling nf-core/circrnasponging ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/circrnasponging/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nf-core/circrnasponging/contents/main.nf

Why I cant open https://nf-co.re/nf-core/circrnasponging/usage, and I cant find circrnasponging  and can only find circrna in nf-core. I am looking forward to your kind reply.

**Comment by nictru** [comment]
Hello,
this pipeline has been created using the nf-core template but is not part of nf-core. We are currently working on merging our pipeline into the nf-core/circrna pipeline, but this will probably take some months.

Our pipeline can be used with the following command:
`nextflow run biomedbigdata/circRNA-sponging <parameters>`. 
Since your pipeline is based on nextflow DSL1, you need to use nextflow version `22.10.x` or earlier. This is one of the reasons we are merging with nf-core/circrna.
As for parameter documentation, you should look into the [repository README](https://github.com/biomedbigdata/circRNA-sponging#basic-workflow).

I hope this allows you to successfully run our pipeline. In case there are any remaining questions, feel free to ask

**Comment by Cesnl** [comment]
Thanks for your kind reply！
but I found that it is difficult to use nextflow 22.10 or earlier version because there may be some wrong in my computer. So hope you can make circrnasponging greater and can work in DLS2 and nextflow 23 in the future. Thanks for your work！
